public enum CastNode {
    case root(CastRootNode)
    case model(CastModelNode)
    case mesh(CastMeshNode)
    case hair(CastHairNode)
    case blendShape(CastBlendShapeNode)
    case skeleton(CastSkeletonNode)
    case bone(CastBoneNode)
    case inverseKinematicsHandle(CastIKHandleNode)
    case constraint(CastConstraintNode)
    case animation(CastAnimationNode)
    case curve(CastCurveNode)
    case curveModeOverride(CastCurveModeOverrideNode)
    case notificationTrack(CastNotificationTrackNode)
    case material(CastMaterialNode)
    case file(CastFileNode)
    case color(CastColorNode)
    case instance(CastInstanceNode)
    case metadata(CastMetadataNode)
}
